export const paisesData = [
    { code: "ad", paisName: "Andorra" },
    { code: "ae", paisName: "United Arab Emirates" },
    { code: "af", paisName: "Afghanistan" },
    { code: "ag", paisName: "Antigua and Barbuda" },
    { code: "ai", paisName: "Anguilla" },
    { code: "al", paisName: "Albania" },
    { code: "am", paisName: "Armenia" },
    { code: "ao", paisName: "Angola" },
    { code: "aq", paisName: "Antarctica" },
    { code: "ar", paisName: "Argentina" },
    { code: "as", paisName: "American Samoa" },
    { code: "at", paisName: "Austria" },
    { code: "au", paisName: "Australia" },
    { code: "aw", paisName: "Aruba" },
    { code: "ax", paisName: "Åland Islands" },
    { code: "az", paisName: "Azerbaijan" },
    { code: "ba", paisName: "Bosnia and Herzegovina" },
    { code: "bb", paisName: "Barbados" },
    { code: "bd", paisName: "Bangladesh" },
    { code: "be", paisName: "Belgium" },
    { code: "bf", paisName: "Burkina Faso" },
    { code: "bg", paisName: "Bulgaria" },
    { code: "bh", paisName: "Bahrain" },
    { code: "bi", paisName: "Burundi" },
    { code: "bj", paisName: "Benin" },
    { code: "bl", paisName: "Saint Barthélemy" },
    { code: "bm", paisName: "Bermuda" },
    { code: "bn", paisName: "Brunei" },
    { code: "bo", paisName: "Bolivia" },
    { code: "bq", paisName: "Caribbean Netherlands" },
    { code: "br", paisName: "Brazil" },
    { code: "bs", paisName: "Bahamas" },
    { code: "bt", paisName: "Bhutan" },
    { code: "bv", paisName: "Bouvet Island" },
    { code: "bw", paisName: "Botswana" },
    { code: "by", paisName: "Belarus" },
    { code: "bz", paisName: "Belize" },
    { code: "ca", paisName: "Canada" },
    { code: "cc", paisName: "Cocos (Keeling) Islands" },
    { code: "cd", paisName: "DR Congo" },
    { code: "cf", paisName: "Central African Republic" },
    { code: "cg", paisName: "Republic of the Congo" },
    { code: "ch", paisName: "Switzerland" },
    { code: "ci", paisName: "Côte d'Ivoire (Ivory Coast)" },
    { code: "ck", paisName: "Cook Islands" },
    { code: "cl", paisName: "Chile" },
    { code: "cm", paisName: "Cameroon" },
    { code: "cn", paisName: "China" },
    { code: "co", paisName: "Colombia" },
    { code: "cr", paisName: "Costa Rica" },
    { code: "cu", paisName: "Cuba" },
    { code: "cv", paisName: "Cape Verde" },
    { code: "cw", paisName: "Curaçao" },
    { code: "cx", paisName: "Christmas Island" },
    { code: "cy", paisName: "Cyprus" },
    { code: "cz", paisName: "Czechia" },
    { code: "de", paisName: "Germany" },
    { code: "dj", paisName: "Djibouti" },
    { code: "dk", paisName: "Denmark" },
    { code: "dm", paisName: "Dominica" },
    { code: "do", paisName: "Dominican Republic" },
    { code: "dz", paisName: "Algeria" },
    { code: "ec", paisName: "Ecuador" },
    { code: "ee", paisName: "Estonia" },
    { code: "eg", paisName: "Egypt" },
    { code: "eh", paisName: "Western Sahara" },
    { code: "er", paisName: "Eritrea" },
    { code: "es", paisName: "Spain" },
    { code: "et", paisName: "Ethiopia" },
    { code: "eu", paisName: "European Union" },
    { code: "fi", paisName: "Finland" },
    { code: "fj", paisName: "Fiji" },
    { code: "fk", paisName: "Falkland Islands" },
    { code: "fm", paisName: "Micronesia" },
    { code: "fo", paisName: "Faroe Islands" },
    { code: "fr", paisName: "France" },
    { code: "ga", paisName: "Gabon" },
    { code: "gb", paisName: "United Kingdom" },
    { code: "gb-eng", paisName: "England" },
    { code: "gb-nir", paisName: "Northern Ireland" },
    { code: "gb-sct", paisName: "Scotland" },
    { code: "gb-wls", paisName: "Wales" },
    { code: "gd", paisName: "Grenada" },
    { code: "ge", paisName: "Georgia" },
    { code: "gf", paisName: "French Guiana" },
    { code: "gg", paisName: "Guernsey" },
    { code: "gh", paisName: "Ghana" },
    { code: "gi", paisName: "Gibraltar" },
    { code: "gl", paisName: "Greenland" },
    { code: "gm", paisName: "Gambia" },
    { code: "gn", paisName: "Guinea" },
    { code: "gp", paisName: "Guadeloupe" },
    { code: "gq", paisName: "Equatorial Guinea" },
    { code: "gr", paisName: "Greece" },
    { code: "gs", paisName: "South Georgia" },
    { code: "gt", paisName: "Guatemala" },
    { code: "gu", paisName: "Guam" },
    { code: "gw", paisName: "Guinea-Bissau" },
    { code: "gy", paisName: "Guyana" },
    { code: "hk", paisName: "Hong Kong" },
    { code: "hm", paisName: "Heard Island and McDonald Islands" },
    { code: "hn", paisName: "Honduras" },
    { code: "hr", paisName: "Croatia" },
    { code: "ht", paisName: "Haiti" },
    { code: "hu", paisName: "Hungary" },
    { code: "id", paisName: "Indonesia" },
    { code: "ie", paisName: "Ireland" },
    { code: "il", paisName: "Israel" },
    { code: "im", paisName: "Isle of Man" },
    { code: "in", paisName: "India" },
    { code: "io", paisName: "British Indian Ocean Territory" },
    { code: "iq", paisName: "Iraq" },
    { code: "ir", paisName: "Iran" },
    { code: "is", paisName: "Iceland" },
    { code: "it", paisName: "Italy" },
    { code: "je", paisName: "Jersey" },
    { code: "jm", paisName: "Jamaica" },
    { code: "jo", paisName: "Jordan" },
    { code: "jp", paisName: "Japan" },
    { code: "ke", paisName: "Kenya" },
    { code: "kg", paisName: "Kyrgyzstan" },
    { code: "kh", paisName: "Cambodia" },
    { code: "ki", paisName: "Kiribati" },
    { code: "km", paisName: "Comoros" },
    { code: "kn", paisName: "Saint Kitts and Nevis" },
    { code: "kp", paisName: "North Korea" },
    { code: "kr", paisName: "South Korea" },
    { code: "kw", paisName: "Kuwait" },
    { code: "ky", paisName: "Cayman Islands" },
    { code: "kz", paisName: "Kazakhstan" },
    { code: "la", paisName: "Laos" },
    { code: "lb", paisName: "Lebanon" },
    { code: "lc", paisName: "Saint Lucia" },
    { code: "li", paisName: "Liechtenstein" },
    { code: "lk", paisName: "Sri Lanka" },
    { code: "lr", paisName: "Liberia" },
    { code: "ls", paisName: "Lesotho" },
    { code: "lt", paisName: "Lithuania" },
    { code: "lu", paisName: "Luxembourg" },
    { code: "lv", paisName: "Latvia" },
    { code: "ly", paisName: "Libya" },
    { code: "ma", paisName: "Morocco" },
    { code: "mc", paisName: "Monaco" },
    { code: "md", paisName: "Moldova" },
    { code: "me", paisName: "Montenegro" },
    { code: "mf", paisName: "Saint Martin" },
    { code: "mg", paisName: "Madagascar" },
    { code: "mh", paisName: "Marshall Islands" },
    { code: "mk", paisName: "North Macedonia" },
    { code: "ml", paisName: "Mali" },
    { code: "mm", paisName: "Myanmar" },
    { code: "mn", paisName: "Mongolia" },
    { code: "mo", paisName: "Macau" },
    { code: "mp", paisName: "Northern Mariana Islands" },
    { code: "mq", paisName: "Martinique" },
    { code: "mr", paisName: "Mauritania" },
    { code: "ms", paisName: "Montserrat" },
    { code: "mt", paisName: "Malta" },
    { code: "mu", paisName: "Mauritius" },
    { code: "mv", paisName: "Maldives" },
    { code: "mw", paisName: "Malawi" },
    { code: "mx", paisName: "Mexico" },
    { code: "my", paisName: "Malaysia" },
    { code: "mz", paisName: "Mozambique" },
    { code: "na", paisName: "Namibia" },
    { code: "nc", paisName: "New Caledonia" },
    { code: "ne", paisName: "Niger" },
    { code: "nf", paisName: "Norfolk Island" },
    { code: "ng", paisName: "Nigeria" },
    { code: "ni", paisName: "Nicaragua" },
    { code: "nl", paisName: "Netherlands" },
    { code: "no", paisName: "Norway" },
    { code: "np", paisName: "Nepal" },
    { code: "nr", paisName: "Nauru" },
    { code: "nu", paisName: "Niue" },
    { code: "nz", paisName: "New Zealand" },
    { code: "om", paisName: "Oman" },
    { code: "pa", paisName: "Panama" },
    { code: "pe", paisName: "Peru" },
    { code: "pf", paisName: "French Polynesia" },
    { code: "pg", paisName: "Papua New Guinea" },
    { code: "ph", paisName: "Philippines" },
    { code: "pk", paisName: "Pakistan" },
    { code: "pl", paisName: "Poland" },
    { code: "pm", paisName: "Saint Pierre and Miquelon" },
    { code: "pn", paisName: "Pitcairn Islands" },
    { code: "pr", paisName: "Puerto Rico" },
    { code: "ps", paisName: "Palestine" },
    { code: "pt", paisName: "Portugal" },
    { code: "pw", paisName: "Palau" },
    { code: "py", paisName: "Paraguay" },
    { code: "qa", paisName: "Qatar" },
    { code: "re", paisName: "Réunion" },
    { code: "ro", paisName: "Romania" },
    { code: "rs", paisName: "Serbia" },
    { code: "ru", paisName: "Russia" },
    { code: "rw", paisName: "Rwanda" },
    { code: "sa", paisName: "Saudi Arabia" },
    { code: "sb", paisName: "Solomon Islands" },
    { code: "sc", paisName: "Seychelles" },
    { code: "sd", paisName: "Sudan" },
    { code: "se", paisName: "Sweden" },
    { code: "sg", paisName: "Singapore" },
    { code: "sh", paisName: "Saint Helena, Ascension and Tristan da Cunha" },
    { code: "si", paisName: "Slovenia" },
    { code: "sj", paisName: "Svalbard and Jan Mayen" },
    { code: "sk", paisName: "Slovakia" },
    { code: "sl", paisName: "Sierra Leone" },
    { code: "sm", paisName: "San Marino" },
    { code: "sn", paisName: "Senegal" },
    { code: "so", paisName: "Somalia" },
    { code: "sr", paisName: "SuripaisName" },
    { code: "ss", paisName: "South Sudan" },
    { code: "st", paisName: "São Tomé and Príncipe" },
    { code: "sv", paisName: "El Salvador" },
    { code: "sx", paisName: "Sint Maarten" },
    { code: "sy", paisName: "Syria" },
    { code: "sz", paisName: "Eswatini (Swaziland)" },
    { code: "tc", paisName: "Turks and Caicos Islands" },
    { code: "td", paisName: "Chad" },
    { code: "tf", paisName: "French Southern and Antarctic Lands" },
    { code: "tg", paisName: "Togo" },
    { code: "th", paisName: "Thailand" },
    { code: "tj", paisName: "Tajikistan" },
    { code: "tk", paisName: "Tokelau" },
    { code: "tl", paisName: "Timor-Leste" },
    { code: "tm", paisName: "Turkmenistan" },
    { code: "tn", paisName: "Tunisia" },
    { code: "to", paisName: "Tonga" },
    { code: "tr", paisName: "Turkey" },
    { code: "tt", paisName: "Trinidad and Tobago" },
    { code: "tv", paisName: "Tuvalu" },
    { code: "tw", paisName: "Taiwan" },
    { code: "tz", paisName: "Tanzania" },
    { code: "ua", paisName: "Ukraine" },
    { code: "ug", paisName: "Uganda" },
    { code: "um", paisName: "United States Minor Outlying Islands" },
    { code: "un", paisName: "United Nations" },
    { code: "us", paisName: "United States" },
    { code: "us-ak", paisName: "Alaska" },
    { code: "us-al", paisName: "Alabama" },
    { code: "us-ar", paisName: "Arkansas" },
    { code: "us-az", paisName: "Arizona" },
    { code: "us-ca", paisName: "California" },
    { code: "us-co", paisName: "Colorado" },
    { code: "us-ct", paisName: "Connecticut" },
    { code: "us-de", paisName: "Delaware" },
    { code: "us-fl", paisName: "Florida" },
    { code: "us-ga", paisName: "Georgia" },
    { code: "us-hi", paisName: "Hawaii" },
    { code: "us-ia", paisName: "Iowa" },
    { code: "us-id", paisName: "Idaho" },
    { code: "us-il", paisName: "Illinois" },
    { code: "us-in", paisName: "Indiana" },
    { code: "us-ks", paisName: "Kansas" },
    { code: "us-ky", paisName: "Kentucky" },
    { code: "us-la", paisName: "Louisiana" },
    { code: "us-ma", paisName: "Massachusetts" },
    { code: "us-md", paisName: "Maryland" },
    { code: "us-me", paisName: "Maine" },
    { code: "us-mi", paisName: "Michigan" },
    { code: "us-mn", paisName: "Minnesota" },
    { code: "us-mo", paisName: "Missouri" },
    { code: "us-ms", paisName: "Mississippi" },
    { code: "us-mt", paisName: "Montana" },
    { code: "us-nc", paisName: "North Carolina" },
    { code: "us-nd", paisName: "North Dakota" },
    { code: "us-ne", paisName: "Nebraska" },
    { code: "us-nh", paisName: "New Hampshire" },
    { code: "us-nj", paisName: "New Jersey" },
    { code: "us-nm", paisName: "New Mexico" },
    { code: "us-nv", paisName: "Nevada" },
    { code: "us-ny", paisName: "New York" },
    { code: "us-oh", paisName: "Ohio" },
    { code: "us-ok", paisName: "Oklahoma" },
    { code: "us-or", paisName: "Oregon" },
    { code: "us-pa", paisName: "Pennsylvania" },
    { code: "us-ri", paisName: "Rhode Island" },
    { code: "us-sc", paisName: "South Carolina" },
    { code: "us-sd", paisName: "South Dakota" },
    { code: "us-tn", paisName: "Tennessee" },
    { code: "us-tx", paisName: "Texas" },
    { code: "us-ut", paisName: "Utah" },
    { code: "us-va", paisName: "Virginia" },
    { code: "us-vt", paisName: "Vermont" },
    { code: "us-wa", paisName: "Washington" },
    { code: "us-wi", paisName: "Wisconsin" },
    { code: "us-wv", paisName: "West Virginia" },
    { code: "us-wy", paisName: "Wyoming" },
    { code: "uy", paisName: "Uruguay" },
    { code: "uz", paisName: "Uzbekistan" },
    { code: "va", paisName: "Vatican City (Holy See)" },
    { code: "vc", paisName: "Saint Vincent and the Grenadines" },
    { code: "ve", paisName: "Venezuela" },
    { code: "vg", paisName: "British Virgin Islands" },
    { code: "vi", paisName: "United States Virgin Islands" },
    { code: "vn", paisName: "Vietnam" },
    { code: "vu", paisName: "Vanuatu" },
    { code: "wf", paisName: "Wallis and Futuna" },
    { code: "ws", paisName: "Samoa" },
    { code: "xk", paisName: "Kosovo" },
    { code: "ye", paisName: "Yemen" },
    { code: "yt", paisName: "Mayotte" },
    { code: "za", paisName: "South Africa" },
    { code: "zm", paisName: "Zambia" },
    { code: "zw", paisName: "Zimbabwe" }
];